<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://austinpyne.github.io/</loc><lastmod>2025-11-14</lastmod></url>
  <url><loc>https://austinpyne.github.io/coding.html</loc><lastmod>2025-11-14</lastmod></url>
  <url><loc>https://austinpyne.github.io/math.html</loc><lastmod>2025-11-13</lastmod></url>
  <url><loc>https://austinpyne.github.io/projects.html</loc><lastmod>2025-11-13</lastmod></url>
  <url><loc>https://austinpyne.github.io/reading.html</loc><lastmod>2025-11-13</lastmod></url>
  <url><loc>https://austinpyne.github.io/writing.html</loc><lastmod>2025-11-14</lastmod></url>
</urlset>
